/* *** DO NOT EDIT THIS FILE! *** */
/* Instead, edit: lang_english.h and rebuild with: */
/* 'make clean ; make ... LANGUAGE=english ...' */

/*
  lang_english.h
  
  Language file for ICBM3D
  English
  
  by Bill Kendrick
  nbs@sonic.net
  http://www.newbreedsoftware.com/
  
  July 29, 1998 - July 29, 1998
  */


/* General: */

#define LANG_LEVEL     "Level"
#define LANG_SCORE     "Score"
#define LANG_GAMEOVER  "Gameover"
#define LANG_PAUSED    "Paused"


/* Title Text: */

#define LANG_SELECT_NEXT_LEVEL  "to select next level"
#define LANG_SELECT_PREV_LEVEL  "to select prev level"
#define LANG_BEGIN              "to begin"
#define LANG_QUIT               "to quit"


/* View Status Text:   (each needs a trailing space!) */

#define LANG_VIEW          "View: "
#define LANG_VIEW_FAST     "Fast "
#define LANG_VIEW_HALF     "Half "
#define LANG_VIEW_MISSILE  "Missile "
#define LANG_VIEW_BULLET   "Bullet "
#define LANG_VIEW_NORMAL   "Normal "


/* Errors and messages: */

#define LANG_ERROR_NODISPLAY  "Can't determine your display!\nPlease specify it on the command line."
#define LANG_CONNECTING       "Connecting to: "
